// <auto-generated />
using System;
using Backend.Domain.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("latin1_swedish_ci")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "latin1");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Model.author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.ToTable("authors");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_hungarian_ci");
                });

            modelBuilder.Entity("Backend.Domain.Model.book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("author_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("boritokep")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cim")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("kiadasi_datum")
                        .HasColumnType("date");

                    b.Property<string>("tartalom")
                        .HasColumnType("text");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "author_id" }, "author_id");

                    b.ToTable("books");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_hungarian_ci");
                });

            modelBuilder.Entity("Backend.Domain.Model.copy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("book_id")
                        .HasColumnType("int(11)");

                    b.Property<bool?>("elerheto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("leltari_szam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "book_id", "elerheto" }, "book_id");

                    b.HasIndex(new[] { "leltari_szam" }, "leltari_szam")
                        .IsUnique();

                    b.ToTable("copies");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_hungarian_ci");
                });

            modelBuilder.Entity("Backend.Domain.Model.rental", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("copy_id")
                        .HasColumnType("int(11)");

                    b.Property<DateOnly>("kolcsonzes_datuma")
                        .HasColumnType("date");

                    b.Property<int>("user_id")
                        .HasColumnType("int(11)");

                    b.Property<DateOnly?>("visszahozva_datuma")
                        .HasColumnType("date");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "copy_id", "visszahozva_datuma" }, "copy_id");

                    b.HasIndex(new[] { "user_id" }, "user_id");

                    b.ToTable("rentals");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_hungarian_ci");
                });

            modelBuilder.Entity("Backend.Domain.Model.users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("jelszo_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("letrehozva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "email" }, "email")
                        .IsUnique();

                    b.ToTable("users");

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_hungarian_ci");
                });

            modelBuilder.Entity("Backend.Domain.Model.book", b =>
                {
                    b.HasOne("Backend.Domain.Model.author", "author")
                        .WithMany("books")
                        .HasForeignKey("author_id")
                        .IsRequired()
                        .HasConstraintName("fk_books_author");

                    b.Navigation("author");
                });

            modelBuilder.Entity("Backend.Domain.Model.copy", b =>
                {
                    b.HasOne("Backend.Domain.Model.book", "book")
                        .WithMany("copies")
                        .HasForeignKey("book_id")
                        .IsRequired()
                        .HasConstraintName("fk_copies_book");

                    b.Navigation("book");
                });

            modelBuilder.Entity("Backend.Domain.Model.rental", b =>
                {
                    b.HasOne("Backend.Domain.Model.copy", "copy")
                        .WithMany("rentals")
                        .HasForeignKey("copy_id")
                        .IsRequired()
                        .HasConstraintName("fk_rentals_copy");

                    b.HasOne("Backend.Domain.Model.users", "user")
                        .WithMany("rentals")
                        .HasForeignKey("user_id")
                        .IsRequired()
                        .HasConstraintName("fk_rentals_user");

                    b.Navigation("copy");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Backend.Domain.Model.author", b =>
                {
                    b.Navigation("books");
                });

            modelBuilder.Entity("Backend.Domain.Model.book", b =>
                {
                    b.Navigation("copies");
                });

            modelBuilder.Entity("Backend.Domain.Model.copy", b =>
                {
                    b.Navigation("rentals");
                });

            modelBuilder.Entity("Backend.Domain.Model.users", b =>
                {
                    b.Navigation("rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
